### ISSUE TITLE
wrong qgis-server address

### ISSUE THREAD

**Issue by jancelin** [3liz/lizmap-docker#1]
Hi,
first try:
docker build -t lizmap_nginx git://github.com/3liz/lizmap-docker 
--> working : 
lizmap_nginx                       latest              a6b0cf755a3e        2 hours ago         632.2 MB

docker run --restart="always" --name "lizmap_nginx" -p 8082:80 -p 8200:8200 -d -t -v /home/jancelin/Bureau/lizmap3:/home -v /home/jancelin/Bureau/lizmap3/run/log:/var/log/lizmap lizmap_nginx
--> working:
 786931d0e230        lizmap_nginx              "/bin/sh -c supervis   2 hours ago         Up About an hour    0.0.0.0:8200->8200/tcp, 0.0.0.0:8082->80/tcp   lizmap_nginx

office and back office ok

But... no map : "service non disponible"
errorlog: 
2016/05/23 12:54:02 [error] 437#0: *206 open() "/srv/lizmap-web-client/lizmap/www/cgi-bin/qgis_mapserv.fcgi" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /cgi-bin/qgis_mapserv.fcgi?map=%2Fhome%2Fcoquelicot%2Eqgs&request=GetCapabilities&service=WFS HTTP/1.0", host: "127.0.0.1"

 wms or wmts address not working:
http://lizmap/index.php/lizmap/service/?repository=test&project=coquelicot&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities

If I try:
http://localhost:8200/lizmap/index.php/lizmap/service/?repository=test&project=coquelicot&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
-->
<ServiceExceptionReport version="1.3.0"><ServiceException code="WMS configuration error">There was an error reading the project file or the SLD configuration</ServiceException></ServiceExceptionReport>

But this address working:
http://127.0.0.1:8200/cgi-bin/qgis_mapserv.fcgi?map=%2Fhome%2Fcoquelicot.qgs&request=GetCapabilities&service=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

I think is a nginx bug... but where? I don't no.

**Comment by jancelin** [comment]
![administration_-_2016-05-23_15 35 31](https://cloud.githubusercontent.com/assets/6421175/15472597/3b97b64e-20fc-11e6-998a-7b62165809ac.png)
sorry I just understood, but it is not instinctive

**Comment by 3liz** [comment]
The path /srv/lizmap-web-client/lizmap/www/cgi-bin/qgis_mapserv.fcg is definitely wrong …..

Nginx does not load any fcgi: it is just proxying  request to a unix socket presforked by supervisor and
thus the request : http://127.0.0.1:8200/cgi-bin/qgis_mapserv.fcgi?map=%2Fhome%2Fcoquelicot.qgs&request=GetCapabilities&service=WMS&VERSION=1.3.0&REQUEST=GetCapabilities http://127.0.0.1:8200/cgi-bin/qgis_mapserv.fcgi?map=/home/coquelicot.qgs&request=GetCapabilities&service=WMS&VERSION=1.3.0&REQUEST=GetCapabilities is invalid.

The port 8200 enables you to access the qgis_server directly, The lizmap application is on the port 80 of the container.

Your url should be something like:

http://localhost:<mapped_port_to_port_80_of_the_container>/lizmap/index.php/lizmap/service/?repository=test&project=coquelicot&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities http://localhost:8200/lizmap/index.php/lizmap/service/?repository=test&project=coquelicot&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities to access Lizmap.

**Comment by jancelin** [comment]
corrected with the addition of the 8200 port to the qgis-server address in the backoffice. 
look at my previous screenshot.

**Comment by dmarteau** [comment]
It should be only http://127.0.0.1:8200/, nginx don't care where the fcgi module is located: it'is just proxying from port 8200 to a fcgi socket.
